#Robot Properties
robot.description=Simple test bot
robot.webpage=
robocode.version=1.10.1
robot.java.source.included=true
robot.author.name=Test
robot.classname=evolved.SimpleBot
robot.name=SimpleBot
