#Robot Properties
robot.description=Evolved bot: Perpendicular + Linear
robot.webpage=
robocode.version=1.10.1
robot.java.source.included=true
robot.author.name=Evolution System
robot.classname=evolved.TestBot
robot.name=TestBot
